[package]
name = "simple-cli-parser"
authors = ["rafesholler"]
version = "0.1.0"
edition = "2024"
description = "A crate for parsing commands and arguemnts passed to the console."
readme = "README.md"
repository = "https://github.com/rafesholler/cli-parser-rust"
license = "MIT"

[dependencies]
